add_executable(cube_3d main.c)
target_link_libraries(cube_3d PRIVATE lumac)
target_include_directories(cube_3d PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../include)
target_compile_definitions(cube_3d PRIVATE LC_TRIANGLE_SPV_DIR="${LC_SPV_DIR}")
if(TARGET lumac_triangle_shaders)
    add_dependencies(cube_3d lumac_triangle_shaders)
endif()
if(UNIX AND NOT APPLE)
    target_link_libraries(cube_3d PRIVATE m)
endif()
