# Hex-to-C converter for embedded SPIR-V (portable, CMake-only).
# Usage: cmake -DIN=<input.spv> -DOUT=<output.c> -DSYM=<symbol> -P hex_to_c.cmake
# Emits: const unsigned char SYM[] = {...}; const unsigned long SYM_size = N;
file(READ "${IN}" HEXDATA HEX)
string(LENGTH "${HEXDATA}" HEXLEN)
# HEXLEN is 2x the byte count; chunk into 0x?? entries, 12 per line.
set(BODY "")
set(LINE_COUNT 0)
set(IDX 0)
while(IDX LESS HEXLEN)
    string(SUBSTRING "${HEXDATA}" ${IDX} 2 BYTEHEX)
    if(LINE_COUNT EQUAL 0)
        string(APPEND BODY "    ")
    endif()
    string(APPEND BODY "0x${BYTEHEX}, ")
    math(EXPR IDX "${IDX} + 2")
    math(EXPR LINE_COUNT "${LINE_COUNT} + 1")
    if(LINE_COUNT EQUAL 12)
        string(APPEND BODY "\n")
        set(LINE_COUNT 0)
    endif()
endwhile()
if(NOT LINE_COUNT EQUAL 0)
    string(APPEND BODY "\n")
endif()
math(EXPR BYTE_COUNT "${HEXLEN} / 2")
file(WRITE "${OUT}" "/* Generated from ${IN}: do not edit. */\n")
file(APPEND "${OUT}" "const unsigned char ${SYM}[] = {\n${BODY}};\n")
file(APPEND "${OUT}" "const unsigned long ${SYM}_size = ${BYTE_COUNT}UL;\n")
