add_executable(render_to_texture main.c)
target_link_libraries(render_to_texture PRIVATE lumac)
target_include_directories(render_to_texture PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../include)
target_compile_definitions(render_to_texture PRIVATE LC_TRIANGLE_SPV_DIR="${LC_SPV_DIR}")
if(TARGET lumac_triangle_shaders)
    add_dependencies(render_to_texture lumac_triangle_shaders)
endif()
if(UNIX AND NOT APPLE)
    target_link_libraries(render_to_texture PRIVATE m)
endif()
